{% set version = "2.4.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sentimentr
  version: {{ version|replace("-", "_") }}

source:
  fn: sentimentr_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/sentimentr_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/sentimentr/sentimentr_{{ version }}.tar.gz
  sha256: 86ae545b563d89bdf058d6fb351cea4f4f0244dba2bb157c5ff90ec1802e945a

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-data.table
    - r-ggplot2
    - r-lexicon >=0.7.4
    - r-stringi
    - r-syuzhet
    - r-textclean >=0.6.1
    - r-textshape >=1.3.0

  run:
    - r-base
    - r-data.table
    - r-ggplot2
    - r-lexicon >=0.7.4
    - r-stringi
    - r-syuzhet
    - r-textclean >=0.6.1
    - r-textshape >=1.3.0

test:
  commands:
    - $R -e "library('sentimentr')"  # [not win]
    - "\"%R%\" -e \"library('sentimentr')\""  # [win]

about:
  home: https://cran.r-project.org/package=sentimentr
  license: MIT
  summary: Calculate text polarity sentiment at the sentence level and optionally aggregate by
    rows or grouping variable(s).
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - CurtLH
