{% set version = "2.9.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sentimentr
  version: {{ version|replace("-", "_") }}

source:
  fn: sentimentr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/sentimentr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sentimentr/sentimentr_{{ version }}.tar.gz
  sha256: 5ba9d517a013054672869cff99d6543856613aec0c5f0ac6963c1d409d781444

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-data.table
    - r-ggplot2
    - r-lexicon >=1.0.0
    - r-stringi
    - r-syuzhet
    - r-textclean >=0.6.1
    - r-textshape >=1.3.0
  run:
    - r-base
    - r-data.table
    - r-ggplot2
    - r-lexicon >=1.0.0
    - r-stringi
    - r-syuzhet
    - r-textclean >=0.6.1
    - r-textshape >=1.3.0

test:
  commands:
    - $R -e "library('sentimentr')"           # [not win]
    - "\"%R%\" -e \"library('sentimentr')\""  # [win]

about:
  home: http://github.com/trinker/sentimentr
  license: MIT
  summary: Calculate text polarity sentiment at the sentence level and optionally aggregate by rows or grouping variable(s).
  license_family: MIT

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
    - CurtLH
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
