{% set version = '2.9.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sentimentr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sentimentr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sentimentr/sentimentr_{{ version }}.tar.gz
  sha256: 5ba9d517a013054672869cff99d6543856613aec0c5f0ac6963c1d409d781444

build:
  number: 5
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-data.table
    - r-ggplot2
    - r-lexicon >=1.2.1
    - r-stringi
    - r-syuzhet
    - r-textclean >=0.6.1
    - r-textshape >=1.3.0
  run:
    - r-base
    - r-data.table
    - r-ggplot2
    - r-lexicon >=1.2.1
    - r-stringi
    - r-syuzhet
    - r-textclean >=0.6.1
    - r-textshape >=1.3.0

test:
  commands:
    - $R -e "library('sentimentr')"           # [not win]
    - "\"%R%\" -e \"library('sentimentr')\""  # [win]

about:
  home: https://github.com/trinker/sentimentr
  license: MIT
  summary: Calculate text polarity sentiment at the sentence level and optionally aggregate by
    rows or grouping variable(s).
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - CurtLH

# Package: sentimentr
# Title: Calculate Text Polarity Sentiment
# Version: 2.9.0
# Authors@R: c(person("Tyler", "Rinker", email = "tyler.rinker@gmail.com", role = c("aut", "cre")))
# Maintainer: Tyler Rinker <tyler.rinker@gmail.com>
# Description: Calculate text polarity sentiment at the sentence level and optionally aggregate by rows or grouping variable(s).
# Depends: R (>= 3.4.0)
# Suggests: testthat
# Imports: data.table, ggplot2, graphics, grid, lexicon (>= 1.2.1), methods, stats, stringi, syuzhet, textclean (>= 0.6.1), textshape (>= 1.3.0), utils
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: TRUE
# RoxygenNote: 7.1.2
# URL: https://github.com/trinker/sentimentr
# BugReports: https://github.com/trinker/sentimentr/issues
# NeedsCompilation: no
# Packaged: 2021-10-12 01:16:43 UTC; TylerRinker
# Author: Tyler Rinker [aut, cre]
# Repository: CRAN
# Date/Publication: 2021-10-12 08:30:02 UTC
