appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: DA1sWceNjxd2JTa7vJc4g2PQ1/hymoblS5UmNiPGqBH8AB0O0yFN7RcS3q0a4+zKxVxXuhHkBgzBBYahjD4/G5PwEl+IC/BpHsR1TTyhv7zY5YW3ymSgxKOu8clv89Yf1WFYKFybeYG+zzz4jWTQxhHxHqNS12ktz82anV7Jc9VbNgwhXBVRCe+1jWMwP36XqPAZb+RGj6Rn/eZERSlafFo9QGGhcFaiu6pShsiwzxPYIqn0+zg8v0PVkca67fCPy5S3pedjHvpkTsEe8AkvGWILQl9OKuVzPS3fjx/3h5XxT3459IDNOoXZ3np/3su3VxBdEuDuGz7uGQ64Z540mdjwsR+cicN+rU5FHv1WPudbxe0Dib0GlIsgh2+3DVsVaEiEcaewUXpPaDq1Mh6XYmhASbiQp1Cg8gbiUu1ajlSje2mHHepnEC08fXnj0r05ofGeRlvVglQMd5JEZ3tlGUBRMzuZDAPQr72JIc0RPqw04biuQ4ukk9NF9BTrRV+n2EM0QYUZx6DOSBgPukZkHPEgF7tJFyHhNPyQr76R3bJZHGhWuFEvA9/GTc+jUd+5E2W7I2HFELSlPy0dujltxBlIr5W4i4r/EZEq6cs1DavfrqAdGHwaHjRVUgpAMY7mv+3zj0N6CQjz5H97a7Jvc/qUKdFY0/I+DQtPDjWrdG4=}
