travis:
  secure:
    BINSTAR_TOKEN: pxJ6Py39++YGCCW3ggxHZzPP5AiJkVWIhE5Wfh1M4n0v23jou0yDJ/uQV9ReDp/cfV/RPljQNHKrcW4Z+pmM/lz45n3w2gLv72EBZq3WBO7he+bDarDjelx+jJ1zqCqsSVr+jBGFKQ4aspDyTrrxEGegdoJySHh0gew/cIX9gSLRmKVyC7cJ4aafxwSdXN7Kmv2Yrm9Dh79jm6bJCAagCXVlqchVBoCVhUnxzzpUnkdyecsXFvX/NiDvzWDyAaEdSY4BCh3MBfrr8PTDWHtm+8DPSnh3EnNqTSH6dzx6nbnY6nGz7XYx3TgrdSFFMWK7Vy7OFjtagp0C2hFw81o4Fg8GTcBxgZ801VADiNgYNsCZ6eQJ7/25ADLSrjNPzB3xaT9wlbmNiujjO83PPqvuDJBqirmm7S9EYKe9E4/YxCBpHBYUyp8whUHPIMuMwWIjGysQ9S+Hgt+GyCuvUIOcGaq3XBvcUwM0C1kcQmbvTm49ke8YJrlPmyy5kMvPh0XsW0ZNB+Cn49jiJWp/4zhrSEcKro2fqTapTRcmNjLiktljgezbkJc847PtWasCRGXl1U1SVd4SFCWpeZKbbrXk7HfTcxQ6vKFKyfEhj9QPRD2R3quHfKxj8zLTFeFcYxi+y/u0QPzU4QsW3THTt2sMYeRlPd1A3BXERP7MDUfcp+M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
